apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-service
  namespace: ci-demo
spec:
  selector:
    app: sample-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

